on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      cuda_ver:
        required: true
        type: string
      linux_ver:
        required: true
        type: string
      py_ver:
        required: true
        type: string
      arch:
        required: true
        type: string
      gpu:
        required: true
        type: string
      driver:
        required: true
        type: string

jobs:
  conda-cpp-tests:
    name: Conda C++ tests
    runs-on:
      - self-hosted
      - linux
      - gpu-${{ inputs.gpu }}-${{ inputs.driver }}-1
      - ${{ inputs.arch }}
    container:
      image: rapidsai/ci:cuda${{ inputs.cuda_ver }}-${{ inputs.linux_ver }}-py${{ inputs.py_ver }}
      env:
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        RAPIDS_PY_VER: ${{ inputs.py_ver }}
        PARALLEL_LEVEL: ${{ env.PARALLEL_LEVEL }}
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: C++ tests
        run: ci/test_cpp.sh
