on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      ref:
        type: string
      repo:
        type: string

jobs:
  conda-upload-packages:
    name: Upload conda packages
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge:latest
      env:
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - name: Upload packages
        run: ci/upload_to_anaconda.sh
