on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

jobs:
  conda-upload-packages:
    name: Upload conda packages
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge:latest
      env:
        BUILD_TYPE: ${{ inputs.build_type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Setup gpuci-tools
        run: |
          git clone https://github.com/Ethyling/gpuci-tools.git -b gha
          cp gpuci-tools/tools/* /usr/local/bin
          rm -rf gpuci-tools
      - name: Upload packages
        run: ci/upload_to_anaconda.sh
