on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

jobs:
  compute-cpp-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      TEST_MATRIX: ${{ steps.compute-matrix.outputs.TEST_MATRIX }}
    steps:
      - name: Compute Python Test Matrix
        id: compute-matrix
        run: |
          PR_TEST_MATRIX='
            [
              { "CUDA_VER": "11.0.3", "LINUX_VER": "centos7", "ARCH": "amd64", "PY_VER": "3.8", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.2.2", "LINUX_VER": "ubuntu18.04", "ARCH": "amd64", "PY_VER": "3.9", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.2.2", "LINUX_VER": "ubuntu18.04", "ARCH": "arm64", "PY_VER": "3.9", "GPU": "a100", "DRIVER": "495" },
              { "CUDA_VER": "11.5.1", "LINUX_VER": "ubuntu20.04", "ARCH": "amd64", "PY_VER": "3.9", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.5.1", "LINUX_VER": "ubuntu20.04", "ARCH": "arm64", "PY_VER": "3.9", "GPU": "a100", "DRIVER": "495" }
            ]
          '

          NIGHTLY_TEST_MATRIX='
            [
              { "CUDA_VER": "11.0.3", "LINUX_VER": "centos7", "ARCH": "amd64", "PY_VER": "3.8", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.2.2", "LINUX_VER": "ubuntu18.04", "ARCH": "amd64", "PY_VER": "3.9", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.2.2", "LINUX_VER": "ubuntu18.04", "ARCH": "arm64", "PY_VER": "3.9", "GPU": "a100", "DRIVER": "495" },
              { "CUDA_VER": "11.5.1", "LINUX_VER": "ubuntu20.04", "ARCH": "amd64", "PY_VER": "3.9", "GPU": "v100", "DRIVER": "495" },
              { "CUDA_VER": "11.5.1", "LINUX_VER": "ubuntu20.04", "ARCH": "arm64", "PY_VER": "3.9", "GPU": "a100", "DRIVER": "495" }
            ]
          '

          if [ "${BUILD_TYPE}" = "nightly" ]; then
            echo "::set-output name=TEST_MATRIX::${NIGHTLY_TEST_MATRIX}"
            echo "nightly"
            exit 0
          fi

          echo "::set-output name=TEST_MATRIX::${PR_TEST_MATRIX}"
          echo "non-nightly"
  tests:
    name: Conda C++ tests
    needs: compute-cpp-test-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{needs.compute-matrix.outputs.TEST_MATRIX}}
    runs-on:
      - self-hosted
      - linux
      - gpu-${{ matrix.GPU }}-${{ matrix.DRIVER }}-1
      - ${{ matrix.ARCH }}
    container:
      image: rapidsai/ci:cuda${{ matrix.CUDA_VER }}-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}
      env:
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        PARALLEL_LEVEL: ${{ env.PARALLEL_LEVEL }}
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: C++ tests
        run: ci/test_cpp.sh
