# A reusable workflow that checks the following:
# - Generated dependency files are up-to-date
# - An "all" environment file is created that includes all of the conda dependencies
#   from the dependencies.yaml file.

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        description: "Location of the dependencies.yaml configuration file"
        default: "dependencies.yaml"
        required: false
        type: string

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rapids-dependency-file-generator
        run: rapids-dependency-file-checker ${{ inputs.CONFIG_FILE_PATH }}
